### ISSUE TITLE
md5/md5_dgst.c: fails to compile with gcc-4.9.0

### ISSUE THREAD

**Issue by austin987** [libressl/portable#8]
Making all in crypto
make[1]: Entering directory '/home/austin/libressl-2.0.0/crypto'
  CC       md5/libcrypto_la-md5_dgst.lo
md5/md5_dgst.c: In function 'md5_block_data_order':
md5/md5_dgst.c:107:49: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  HOST_c2l(data,l); X( 0)=l;  HOST_c2l(data,l); X( 1)=l;
                                                 ^
md5/md5_dgst.c:107:109: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  HOST_c2l(data,l); X( 0)=l;  HOST_c2l(data,l); X( 1)=l;
                                                                                                             ^
md5/md5_dgst.c:109:168: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(A,B,C,D,X( 0), 7,0xd76aa478L); HOST_c2l(data,l); X( 2)=l;
                                                                                                                                                                        ^
md5/md5_dgst.c:110:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(D,A,B,C,X( 1),12,0xe8c7b756L); HOST_c2l(data,l); X( 3)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:111:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(C,D,A,B,X( 2),17,0x242070dbL); HOST_c2l(data,l); X( 4)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:112:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(B,C,D,A,X( 3),22,0xc1bdceeeL); HOST_c2l(data,l); X( 5)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:113:168: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(A,B,C,D,X( 4), 7,0xf57c0fafL); HOST_c2l(data,l); X( 6)=l;
                                                                                                                                                                        ^
md5/md5_dgst.c:114:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(D,A,B,C,X( 5),12,0x4787c62aL); HOST_c2l(data,l); X( 7)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:115:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(C,D,A,B,X( 6),17,0xa8304613L); HOST_c2l(data,l); X( 8)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:116:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(B,C,D,A,X( 7),22,0xfd469501L); HOST_c2l(data,l); X( 9)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:117:168: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(A,B,C,D,X( 8), 7,0x698098d8L); HOST_c2l(data,l); X(10)=l;
                                                                                                                                                                        ^
md5/md5_dgst.c:118:170: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(D,A,B,C,X( 9),12,0x8b44f7afL); HOST_c2l(data,l); X(11)=l;
                                                                                                                                                                          ^
md5/md5_dgst.c:119:171: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(C,D,A,B,X(10),17,0xffff5bb1L); HOST_c2l(data,l); X(12)=l;
                                                                                                                                                                           ^
md5/md5_dgst.c:120:171: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(B,C,D,A,X(11),22,0x895cd7beL); HOST_c2l(data,l); X(13)=l;
                                                                                                                                                                           ^
md5/md5_dgst.c:121:169: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(A,B,C,D,X(12), 7,0x6b901122L); HOST_c2l(data,l); X(14)=l;
                                                                                                                                                                         ^
md5/md5_dgst.c:122:171: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
  R0(D,A,B,C,X(13),12,0xfd987193L); HOST_c2l(data,l); X(15)=l;
                                                                                                                                                                           ^
cc1: all warnings being treated as errors
Makefile:5417: recipe for target 'md5/libcrypto_la-md5_dgst.lo' failed
make[1]: **\* [md5/libcrypto_la-md5_dgst.lo] Error 1
make[1]: Leaving directory '/home/austin/libressl-2.0.0/crypto'
Makefile:381: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1
