### ISSUE TITLE
Missing SSL_CONF_*() functions in LibreSSL 3.7.x

### ISSUE THREAD

**Issue by orbea** [libressl/portable#851]
These are used by ettercap.

https://github.com/Ettercap/ettercap/blob/f03a1174ffccf9343423498fa3c65bd9090d4ce0/src/ec_sslwrap.c#L1135-L1149
```
samu: job failed: /usr/lib/ccache/bin/cc -Dlib_ettercap_EXPORTS -I/usr/include/gtk-3.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/tmp/ettercap/build/include -I/tmp/ettercap/include -I/usr/include/ncurses -I/tmp/ettercap/src/interfaces/daemon -I/tmp/ettercap/src/interfaces/text -I/tmp/ettercap/src/interfaces/curses -I/tmp/ettercap/src/interfaces/curses/widgets -O2 -w -D_FORTIFY_SOURCE=2 -fPIC -MD -MT src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o -MF src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o.d -o src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o -c /tmp/ettercap/src/ec_sslwrap.c
/tmp/ettercap/src/ec_sslwrap.c:145:8: error: unknown type name 'SSL_CONF_CTX'
  145 | static SSL_CONF_CTX *ssl_conf_client, *ssl_conf_server;
      |        ^~~~~~~~~~~~
/tmp/ettercap/src/ec_sslwrap.c: In function 'sslw_init':
/tmp/ettercap/src/ec_sslwrap.c:1138:44: error: 'SSL_CONF_FLAG_FILE' undeclared (first use in this function)
 1138 |    SSL_CONF_CTX_set_flags(ssl_conf_client, SSL_CONF_FLAG_FILE);
      |                                            ^~~~~~~~~~~~~~~~~~
/tmp/ettercap/src/ec_sslwrap.c:1138:44: note: each undeclared identifier is reported only once for each function it appears in
samu: subcommand failed
```
Where build failures were hidden when using LibreSSL in commit https://github.com/Ettercap/ettercap/commit/b2fc8e959dc71fdbaba08aecb1f157c914490a07.

**Comment by orbea** [comment]
Actually now I see a issue for this here. https://github.com/libressl/openbsd/issues/113

I'm not sure which would be preferable to keep?

**Comment by 4a6f656c** [comment]
I'll close this in favour of #890.
